// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// KnowledgeFile is the predicate function for knowledgefile builders.
type KnowledgeFile func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
