services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 将编译后的前端文件传递给 nginx
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  frontend-dist:
