// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ppt-stasher-backend/ent/knowledgefile"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// KnowledgeFile is the model entity for the KnowledgeFile schema.
type KnowledgeFile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 文件名
	FileName string `json:"file_name,omitempty"`
	// 文件类型 (pdf, docx, txt)
	FileType string `json:"file_type,omitempty"`
	// 大模型生成的摘要或用户手动修改的描述
	Description string `json:"description,omitempty"`
	// 本地存储全路径
	StoragePath string `json:"storage_path,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KnowledgeFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case knowledgefile.FieldID:
			values[i] = new(sql.NullInt64)
		case knowledgefile.FieldFileName, knowledgefile.FieldFileType, knowledgefile.FieldDescription, knowledgefile.FieldStoragePath:
			values[i] = new(sql.NullString)
		case knowledgefile.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KnowledgeFile fields.
func (_m *KnowledgeFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case knowledgefile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case knowledgefile.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case knowledgefile.FieldFileType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_type", values[i])
			} else if value.Valid {
				_m.FileType = value.String
			}
		case knowledgefile.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case knowledgefile.FieldStoragePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_path", values[i])
			} else if value.Valid {
				_m.StoragePath = value.String
			}
		case knowledgefile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KnowledgeFile.
// This includes values selected through modifiers, order, etc.
func (_m *KnowledgeFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this KnowledgeFile.
// Note that you need to call KnowledgeFile.Unwrap() before calling this method if this KnowledgeFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KnowledgeFile) Update() *KnowledgeFileUpdateOne {
	return NewKnowledgeFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KnowledgeFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KnowledgeFile) Unwrap() *KnowledgeFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KnowledgeFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KnowledgeFile) String() string {
	var builder strings.Builder
	builder.WriteString("KnowledgeFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("file_type=")
	builder.WriteString(_m.FileType)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("storage_path=")
	builder.WriteString(_m.StoragePath)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// KnowledgeFiles is a parsable slice of KnowledgeFile.
type KnowledgeFiles []*KnowledgeFile
