// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ppt-stasher-backend/ent/knowledgefile"
	"ppt-stasher-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KnowledgeFileUpdate is the builder for updating KnowledgeFile entities.
type KnowledgeFileUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeFileMutation
}

// Where appends a list predicates to the KnowledgeFileUpdate builder.
func (_u *KnowledgeFileUpdate) Where(ps ...predicate.KnowledgeFile) *KnowledgeFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *KnowledgeFileUpdate) SetFileName(v string) *KnowledgeFileUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableFileName(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *KnowledgeFileUpdate) SetFileType(v string) *KnowledgeFileUpdate {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableFileType(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeFileUpdate) SetDescription(v string) *KnowledgeFileUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableDescription(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeFileUpdate) ClearDescription() *KnowledgeFileUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *KnowledgeFileUpdate) SetStoragePath(v string) *KnowledgeFileUpdate {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableStoragePath(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// Mutation returns the KnowledgeFileMutation object of the builder.
func (_u *KnowledgeFileUpdate) Mutation() *KnowledgeFileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFileUpdate) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := knowledgefile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := knowledgefile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoragePath(); ok {
		if err := knowledgefile.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.storage_path": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefile.Table, knowledgefile.Columns, sqlgraph.NewFieldSpec(knowledgefile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(knowledgefile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(knowledgefile.FieldFileType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgefile.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgefile.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(knowledgefile.FieldStoragePath, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeFileUpdateOne is the builder for updating a single KnowledgeFile entity.
type KnowledgeFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeFileMutation
}

// SetFileName sets the "file_name" field.
func (_u *KnowledgeFileUpdateOne) SetFileName(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableFileName(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *KnowledgeFileUpdateOne) SetFileType(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableFileType(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *KnowledgeFileUpdateOne) SetDescription(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableDescription(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *KnowledgeFileUpdateOne) ClearDescription() *KnowledgeFileUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *KnowledgeFileUpdateOne) SetStoragePath(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableStoragePath(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// Mutation returns the KnowledgeFileMutation object of the builder.
func (_u *KnowledgeFileUpdateOne) Mutation() *KnowledgeFileMutation {
	return _u.mutation
}

// Where appends a list predicates to the KnowledgeFileUpdate builder.
func (_u *KnowledgeFileUpdateOne) Where(ps ...predicate.KnowledgeFile) *KnowledgeFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeFileUpdateOne) Select(field string, fields ...string) *KnowledgeFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeFile entity.
func (_u *KnowledgeFileUpdateOne) Save(ctx context.Context) (*KnowledgeFile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFileUpdateOne) SaveX(ctx context.Context) *KnowledgeFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFileUpdateOne) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := knowledgefile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := knowledgefile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoragePath(); ok {
		if err := knowledgefile.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.storage_path": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeFileUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefile.Table, knowledgefile.Columns, sqlgraph.NewFieldSpec(knowledgefile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgefile.FieldID)
		for _, f := range fields {
			if !knowledgefile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgefile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(knowledgefile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(knowledgefile.FieldFileType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(knowledgefile.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(knowledgefile.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(knowledgefile.FieldStoragePath, field.TypeString, value)
	}
	_node = &KnowledgeFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
