// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ppt-stasher-backend/ent/knowledgefile"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KnowledgeFileCreate is the builder for creating a KnowledgeFile entity.
type KnowledgeFileCreate struct {
	config
	mutation *KnowledgeFileMutation
	hooks    []Hook
}

// SetFileName sets the "file_name" field.
func (_c *KnowledgeFileCreate) SetFileName(v string) *KnowledgeFileCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetFileType sets the "file_type" field.
func (_c *KnowledgeFileCreate) SetFileType(v string) *KnowledgeFileCreate {
	_c.mutation.SetFileType(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *KnowledgeFileCreate) SetDescription(v string) *KnowledgeFileCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableDescription(v *string) *KnowledgeFileCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStoragePath sets the "storage_path" field.
func (_c *KnowledgeFileCreate) SetStoragePath(v string) *KnowledgeFileCreate {
	_c.mutation.SetStoragePath(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KnowledgeFileCreate) SetCreatedAt(v time.Time) *KnowledgeFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableCreatedAt(v *time.Time) *KnowledgeFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the KnowledgeFileMutation object of the builder.
func (_c *KnowledgeFileCreate) Mutation() *KnowledgeFileMutation {
	return _c.mutation
}

// Save creates the KnowledgeFile in the database.
func (_c *KnowledgeFileCreate) Save(ctx context.Context) (*KnowledgeFile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KnowledgeFileCreate) SaveX(ctx context.Context) *KnowledgeFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KnowledgeFileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := knowledgefile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KnowledgeFileCreate) check() error {
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "KnowledgeFile.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := knowledgefile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileType(); !ok {
		return &ValidationError{Name: "file_type", err: errors.New(`ent: missing required field "KnowledgeFile.file_type"`)}
	}
	if v, ok := _c.mutation.FileType(); ok {
		if err := knowledgefile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StoragePath(); !ok {
		return &ValidationError{Name: "storage_path", err: errors.New(`ent: missing required field "KnowledgeFile.storage_path"`)}
	}
	if v, ok := _c.mutation.StoragePath(); ok {
		if err := knowledgefile.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.storage_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KnowledgeFile.created_at"`)}
	}
	return nil
}

func (_c *KnowledgeFileCreate) sqlSave(ctx context.Context) (*KnowledgeFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KnowledgeFileCreate) createSpec() (*KnowledgeFile, *sqlgraph.CreateSpec) {
	var (
		_node = &KnowledgeFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(knowledgefile.Table, sqlgraph.NewFieldSpec(knowledgefile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(knowledgefile.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileType(); ok {
		_spec.SetField(knowledgefile.FieldFileType, field.TypeString, value)
		_node.FileType = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(knowledgefile.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.StoragePath(); ok {
		_spec.SetField(knowledgefile.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgefile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// KnowledgeFileCreateBulk is the builder for creating many KnowledgeFile entities in bulk.
type KnowledgeFileCreateBulk struct {
	config
	err      error
	builders []*KnowledgeFileCreate
}

// Save creates the KnowledgeFile entities in the database.
func (_c *KnowledgeFileCreateBulk) Save(ctx context.Context) ([]*KnowledgeFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KnowledgeFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KnowledgeFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KnowledgeFileCreateBulk) SaveX(ctx context.Context) []*KnowledgeFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
