// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ppt-stasher-backend/ent/knowledgefile"
	"ppt-stasher-backend/ent/schema"
	"ppt-stasher-backend/ent/task"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	knowledgefileFields := schema.KnowledgeFile{}.Fields()
	_ = knowledgefileFields
	// knowledgefileDescFileName is the schema descriptor for file_name field.
	knowledgefileDescFileName := knowledgefileFields[0].Descriptor()
	// knowledgefile.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	knowledgefile.FileNameValidator = knowledgefileDescFileName.Validators[0].(func(string) error)
	// knowledgefileDescFileType is the schema descriptor for file_type field.
	knowledgefileDescFileType := knowledgefileFields[1].Descriptor()
	// knowledgefile.FileTypeValidator is a validator for the "file_type" field. It is called by the builders before save.
	knowledgefile.FileTypeValidator = knowledgefileDescFileType.Validators[0].(func(string) error)
	// knowledgefileDescStoragePath is the schema descriptor for storage_path field.
	knowledgefileDescStoragePath := knowledgefileFields[3].Descriptor()
	// knowledgefile.StoragePathValidator is a validator for the "storage_path" field. It is called by the builders before save.
	knowledgefile.StoragePathValidator = knowledgefileDescStoragePath.Validators[0].(func(string) error)
	// knowledgefileDescCreatedAt is the schema descriptor for created_at field.
	knowledgefileDescCreatedAt := knowledgefileFields[4].Descriptor()
	// knowledgefile.DefaultCreatedAt holds the default value on creation for the created_at field.
	knowledgefile.DefaultCreatedAt = knowledgefileDescCreatedAt.Default.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTheme is the schema descriptor for theme field.
	taskDescTheme := taskFields[0].Descriptor()
	// task.ThemeValidator is a validator for the "theme" field. It is called by the builders before save.
	task.ThemeValidator = taskDescTheme.Validators[0].(func(string) error)
	// taskDescStatus is the schema descriptor for status field.
	taskDescStatus := taskFields[1].Descriptor()
	// task.DefaultStatus holds the default value on creation for the status field.
	task.DefaultStatus = taskDescStatus.Default.(string)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[3].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
}
