// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// KnowledgeFilesColumns holds the columns for the "knowledge_files" table.
	KnowledgeFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "file_name", Type: field.TypeString},
		{Name: "file_type", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "storage_path", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// KnowledgeFilesTable holds the schema information for the "knowledge_files" table.
	KnowledgeFilesTable = &schema.Table{
		Name:       "knowledge_files",
		Columns:    KnowledgeFilesColumns,
		PrimaryKey: []*schema.Column{KnowledgeFilesColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "theme", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "result_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		KnowledgeFilesTable,
		TasksTable,
	}
)

func init() {
}
